servidor_mail:
  image: mailhog/mailhog
  ports:
    - "8082:8025"
  environment:
    - "MH_SMTP_BIND_ADDR=0.0.0.0:25"
  expose:
    - "25"

servidor_web:
  build: servidor_web
  links:
    - servidor_mail
  ports:
    - "8081:80"
  volumes:
    - ./web_comercial:/var/www/html:Z

minify:
  build: minify
  volumes:
    - "./web_comercial:/usr/src/app/app:Z"
